### ISSUE TITLE
why did you only use small data for train not all train data

### ISSUE THREAD

**Issue by Usernamezhx** [psinger/kaggle-landmark-recognition-2020-1st-place#2]
first of all. thanks for your cool work. why not use all train data to train model ?
https://github.com/psinger/kaggle-landmark-recognition-2020-1st-place/blob/a4a467143b12315a784e91dcb3fc332cdcb5cc27/src/train.py#L93

**Comment by psinger** [comment]
Thanks for noting this, should obviously not be there and is likely a leftover from debug mode.
